### PR TITLE
Replace deprecated 'bio' field with 'about' and upgrade FB Graph API …

### LINKED ISSUE #740: FacebookClient and Facebook API 2.8
I trying to use FacebookClient (pac4j-oauth 1.9.3) with newly created FB application. Now all new apps will be created with api version 2.8 and this version cannot be downgraded, and I getting following error:
`[HttpCommunicationException: Failed to retrieve data / failed code : 400 and body : {"error":{"message":"(#12) bio field is deprecated for versions v2.8 and higher","type":"OAuthException","code":12,"fbtrace_id":"F\/E87eGaogN"}}]
`

### PR DESCRIPTION
**Pull request by ArkadyKarev**
…version up to 2.8. Fix #740

### CODE REVIEW

File: pac4j-oauth/src/main/java/org/pac4j/oauth/profile/facebook/FacebookProfile.java [hunk 1]
```diff
@@ -57,127 +57,138 @@ public String getLocation() {
...
         return (Date) getAttribute(FacebookAttributesDefinition.UPDATED_TIME);
     }
-    
+
     public Boolean getVerified() {
         return (Boolean) getAttribute(FacebookAttributesDefinition.VERIFIED);
     }
-    
+
+	/**
```
Comment (leleuj) [inline pac4j-oauth/src/main/java/org/pac4j/oauth/profile/facebook/FacebookProfile.java]: Master is at version 2.0.0, which is a major one with potential breaking changes.

So you can safely remove this method.

**Comment by ArkadyKarev** [comment]
@leleuj done!

**Comment by leleuj** [comment]
Perfect. Thanks.
